### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by stleon** [JulianEberius/SublimePythonIDE#78]
OS X El Capitan, Python 3.

Enable SublimePythonIDE, in sublime console:
```
reloading Packages/SublimePythonIDE/SublimePython.sublime-settings
Traceback (most recent call last):
  File "/Users/user_name/Library/Application Support/Sublime Text 3/Packages/SublimePythonIDE/sublime_python.py", line 412, in _update_color_scheme
    "warning": get_setting("warning_color"),
TypeError: 'NoneType' object is not callable
```

**Comment by JulianEberius** [comment]
Should be fixed in current master. Thanks for reporting.

**Comment by kamakazikamikaze** [comment]
I've uninstalled and re-installed SublimePythonIDE, checking that the version is 1.0.3, however I'm seeing a similar error:

    Traceback (most recent call last):
      File "C:\Users\username\AppData\Roaming\Sublime Text 3\Packages\SublimePythonIDE\sublime_python.py", line 492, in _update_color_scheme
    "warning": get_setting("warning_color", default_value="EDBA00"),
    TypeError: 'NoneType' object is not callable

Warning and errors messages from linter are not being shown, but the first line that invokes the warning/error will be highlighted. 


Windows 10 64-bit, Python 2.7

I've uninstalled all other packages to see if there was a conflict, however nothing seems to have resolved this issue.
